config/routes.rb
Rails.application.routes.draw do
  root to: 'objects#new'
  resources :objects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/objects_controller.rb
class ObjectsController < ApplicationController
  def new
    @redis = $redis.keys
  end

  def create
    $redis.set(params[:key], params[:value])
    redirect_to root_path
  end

  def destroy
    $redis.del(params[:id])
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/objects_helper.rb
module ObjectsHelper
  def get_value(key)
    $redis.get(key) if $redis.type(key) == 'string'
  end

  def get_type(key)
    $redis.type(key)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedisClient</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>
</html>

app/views/objects/create.html.erb
<h1> Object created </h1>

app/views/objects/new.html.erb
<h1> Add new object </h1>

<%= form_tag(objects_path, method: :post) do %>
<p>
  Key:<br />
  <%= text_field_tag :key %>
</p><p>
  Value:<br />
  <%= text_field_tag :value %>
</p>
 <p>
   <%= submit_tag 'Submit' %>
 </p>
<% end %>

<h1> List string values </h1>
<%- @redis.each do |k| %>
  <h2><%= k %> </h2>
  <p>
    <%= "Is a type of: #{get_type(k)}" %>
  </p>
  <p>
    <%= "and has a value of: #{get_value(k)}" %>
  </p>
  <p>
    <%=link_to 'Delete', object_path(k), :method => :delete %>
  </p>
<% end %>
<h2> sdfa </h2>
<%- @redis.each do |x| %>
  <%= p $redis.type(x) %>
<% end %>